name: project_vision
description: AI-Powered Project Scaffolding Tool
publish_to: 'none' # Remove this line if you intend to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjusted based on typical Flutter project requirements

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6
  http: any # Consider updating to a newer version if available e.g. ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  firebase_core: any
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  flutter_markdown: ^0.7.7+1
  pdf: ^3.10.1
  url_launcher: ^6.1.11
  share_plus: ^11.0.0
  flutter_quill: ^11.4.1
  macos_ui: ^2.1.10
  firebase_ai: any
  macos_window_utils: any
  uuid: ^4.3.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 # Or a newer version
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
