import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:project_vision/app.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:firebase_core/firebase_core.dart'; // Import Firebase Core
import 'firebase_options.dart'; // Import Firebase Options (generated by FlutterFire CLI)

void main() async { // Ensure main is async
  WidgetsFlutterBinding.ensureInitialized(); // Already present

  // Initialize Firebase
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    print("Firebase initialized successfully.");
  } catch (e) {
    // It's crucial to handle Firebase initialization errors.
    // Depending on the app's needs, you might want to:
    // 1. Show an error screen.
    // 2. Log the error and continue if some parts of the app can work without Firebase.
    // 3. For this app, AI features depend on Firebase, so an error is critical.
    print("Error initializing Firebase: $e");
    // Optionally, you could rethrow or set a global error state.
    // For now, we'll print and continue, but GeminiService will likely fail.
  }

  // Initialize Hive (already present)
  await Hive.initFlutter();
  // TODO: Open Hive boxes if any are used at startup
  // Example: await Hive.openBox('settings');

  runApp(
    const ProviderScope( // Make ProviderScope const if its child is const
      child: ProjectVisionApp(),
    ),
  );
}
