import 'package:flutter/cupertino.dart';
import 'package:macos_ui/macos_ui.dart';
import 'package:flutter/material.dart'; // Required for FlutterLogo
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:project_vision/providers/ai_provider.dart';
import 'package:project_vision/models/expanded_project_idea.dart';
import 'package:project_vision/models/guided_question.dart';
import 'package:project_vision/models/project_data.dart';
// import 'package:uuid/uuid.dart'; // Uuid can be removed if ID is generated by service
import 'package:project_vision/providers/storage_provider.dart'; // New import
// project_feature.dart and project_risk.dart are implicitly imported via expanded_project_idea.dart
// but could be explicitly imported if direct instantiation or type usage was needed here.

class IdeaInputScreen extends ConsumerStatefulWidget {
  const IdeaInputScreen({super.key});

  @override
  ConsumerState<IdeaInputScreen> createState() => _IdeaInputScreenState();
}

class _IdeaInputScreenState extends ConsumerState<IdeaInputScreen> {
  final _projectConceptController = TextEditingController();
  final _projectGoalsController = TextEditingController();
  final _targetAudienceController = TextEditingController();
  bool _isLoading = false;
  bool _showGuidedQuestions = false; // Toggle for showing/hiding questionnaire
  ExpandedProjectIdea? _latestAIExpansionResult;

  final List<Map<String, String>> _initialQuestionsData = [
    {'id': 'problem', 'text': 'What specific problem does your project aim to solve?'},
    {'id': 'mvp_features', 'text': 'What are 2-3 core features essential for an MVP (Minimum Viable Product)?'},
    {'id': 'unique_value', 'text': 'What makes your project unique compared to potential alternatives?'},
    {'id': 'success_metrics', 'text': 'What are the primary success metrics for this project?'},
  ];

  List<GuidedQuestion> _guidedQuestionList = [];
  Map<String, TextEditingController> _guidedQuestionControllers = {};

  final Map<String, List<String>> _projectCategoriesDefinition = {
    'Project Type': [
      'Mobile App', 'Web Application', 'Desktop Application', 'Game',
      'API/Backend Service', 'AI/ML Project', 'IoT Project', 'Other'
    ],
    'Industry': [
      'Healthcare', 'Finance/Fintech', 'Education/EdTech', 'E-commerce/Retail',
      'Productivity/Tools', 'Social Media/Networking', 'Entertainment',
      'Travel/Hospitality', 'Real Estate', 'Manufacturing', 'Other'
    ],
    'Project Scale': [
      'Personal/Solo', 'Small Team (2-5 people)', 'Medium Team (6-15 people)',
      'Large Team (16+ people)', 'Enterprise Level'
    ],
  };

  Map<String, String?> _selectedCategories = {
    'Project Type': null,
    'Industry': null,
    'Project Scale': null,
  };

  @override
  void initState() {
    super.initState();
    // Existing controllers for project concept, goals, audience are already initialized

    for (var qData in _initialQuestionsData) {
      _guidedQuestionList.add(GuidedQuestion(id: qData['id']!, text: qData['text']!));
      _guidedQuestionControllers[qData['id']!] = TextEditingController();
    }
  }

  @override
  void dispose() {
    _projectConceptController.dispose();
    _projectGoalsController.dispose();
    _targetAudienceController.dispose();
    for (var controller in _guidedQuestionControllers.values) {
      controller.dispose();
    }
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MacosScaffold(
      toolBar: ToolBar(
        title: const Text('New Project Idea'),
        leading: MacosBackButton(
          onPressed: () => Navigator.of(context).pop(),
        ),
      ),
      children: [
        ContentArea(
          builder: (context, scrollController) {
            return SingleChildScrollView(
              controller: scrollController,
              padding: const EdgeInsets.all(20.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'Describe Your Project Concept',
                    style: MacosTheme.of(context).typography.title2,
                  ),
                  const SizedBox(height: 8),
                  MacosTextField(
                    controller: _projectConceptController,
                    placeholder: 'Enter a detailed description of your project idea...',
                    maxLines: 10,
                    minLines: 5,
                  ),
                  const SizedBox(height: 24),

                  // Guided Questionnaire Toggle and Section
                  MacosSwitch(
                    value: _showGuidedQuestions,
                    onChanged: (value) {
                      setState(() {
                        _showGuidedQuestions = value;
                      });
                    },
                  ),
                  const SizedBox(width: 8),
                  const Text('Use Guided Questionnaire (Optional)'),

                  if (_showGuidedQuestions)
                    Padding(
                      padding: const EdgeInsets.only(top: 16.0, left: 8.0, right: 8.0),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            'Guided Questions:',
                            style: MacosTheme.of(context).typography.headline,
                          ),
                          const SizedBox(height: 12),
                          ..._guidedQuestionList.map((question) {
                            return Padding(
                              padding: const EdgeInsets.only(bottom: 16.0),
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(question.text, style: MacosTheme.of(context).typography.body),
                                  const SizedBox(height: 6),
                                  MacosTextField(
                                    controller: _guidedQuestionControllers[question.id],
                                    placeholder: 'Your answer...',
                                    maxLines: 2,
                                  ),
                                ],
                              ),
                            );
                          }).toList(),
                        ],
                      ),
                    ),
                  const SizedBox(height: 24), // Existing SizedBox before Project Categorization placeholder

                  // Project Categorization Section
                  Text(
                    'Project Categorization',
                    style: MacosTheme.of(context).typography.headline,
                  ),
                  const SizedBox(height: 12),

                  ..._projectCategoriesDefinition.entries.map((entry) {
                    final categoryName = entry.key;
                    final options = entry.value;
                    return Padding(
                      padding: const EdgeInsets.only(bottom: 16.0),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(categoryName, style: MacosTheme.of(context).typography.body),
                          const SizedBox(height: 6),
                          MacosPopupButton<String>(
                            value: _selectedCategories[categoryName],
                            // Hint to show when no value is selected
                            hint: Text('Select $categoryName...'),
                            onChanged: (String? newValue) {
                              setState(() {
                                _selectedCategories[categoryName] = newValue;
                              });
                            },
                            items: options.map<MacosPopupMenuItem<String>>((String value) {
                              return MacosPopupMenuItem<String>(
                                value: value,
                                child: Text(value),
                              );
                            }).toList(),
                          ),
                        ],
                      ),
                    );
                  }).toList(),
                  const SizedBox(height: 24), // Add some space

                  // Project Goals
                  Text(
                    'Project Goals',
                    style: MacosTheme.of(context).typography.headline,
                  ),
                  const SizedBox(height: 8),
                  MacosTextField(
                    controller: _projectGoalsController, // Needs to be created
                    placeholder: 'What are the main goals of this project?',
                    maxLines: 5,
                    minLines: 3,
                  ),
                  const SizedBox(height: 24),

                  // Target Audience
                  Text(
                    'Target Audience',
                    style: MacosTheme.of(context).typography.headline,
                  ),
                  const SizedBox(height: 8),
                  MacosTextField(
                    controller: _targetAudienceController, // Needs to be created
                    placeholder: 'Who is the target audience for this project?',
                    maxLines: 5,
                    minLines: 3,
                  ),
                  const SizedBox(height: 30),

                  // Modify the existing Align to include two buttons in a Row
                  Align(
                    alignment: Alignment.centerRight,
                    child: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        PushButton(
                          buttonSize: ButtonSize.large,
                          secondary: true, // Make it look like a secondary action initially
                          onPressed: _handleSaveProject, // New handler function
                          child: const Text('Save Project'),
                        ),
                        const SizedBox(width: 12),
                        PushButton(
                          buttonSize: ButtonSize.large,
                          onPressed: _isLoading ? null : _handleAnalyzeProject, // Existing handler, rename for clarity
                          child: _isLoading
                              ? const ProgressCircle(value: null)
                              : const Text('Analyze Idea'), // Renamed from "Next: Add Context"
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            );
          },
        ),
      ],
    );
  }

  Future<void> _handleAnalyzeProject() async { // Renamed handler
    final concept = _projectConceptController.text;
    final goals = _projectGoalsController.text;
    final audience = _targetAudienceController.text;

    if (concept.isEmpty) {
      showMacosAlertDialog(
        context: context,
        builder: (_) => MacosAlertDialog(
          appIcon: const MacosIcon(CupertinoIcons.exclamationmark_triangle, size: 56),
          title: Text('Concept Missing', style: MacosTheme.of(context).typography.headline),
          message: Text('Please enter your project concept before proceeding. Goals and audience are optional for now.', style: MacosTheme.of(context).typography.body),
          primaryButton: PushButton(
            buttonSize: ButtonSize.large,
            child: const Text('OK'),
            onPressed: () => Navigator.of(context).pop(),
          ),
        ),
      );
      return; // Stop execution if concept is empty
    }

    setState(() {
      _isLoading = true;
    });

    // Collect questionnaire answers
    Map<String, String> collectedQuestionnaireAnswers = {};
    if (_showGuidedQuestions) { // Only collect if the questionnaire is visible and used
      _guidedQuestionControllers.forEach((id, controller) {
        if (controller.text.trim().isNotEmpty) {
          final questionText = _guidedQuestionList.firstWhere((q) => q.id == id, orElse: () => GuidedQuestion(id: id, text: id)).text;
          collectedQuestionnaireAnswers[questionText] = controller.text.trim();
        }
      });
    }

    // Collect project categories
    Map<String, String> finalSelectedCategories = {};
    _selectedCategories.forEach((categoryName, selectedOption) {
      if (selectedOption != null && selectedOption.isNotEmpty) {
        finalSelectedCategories[categoryName] = selectedOption;
      }
    });

    try {
      final aiService = ref.read(aiServiceProvider);
      final analysisResult = await aiService.analyzeProjectIdea(
        concept: concept,
        goals: goals,
        audience: audience,
        questionnaireAnswers: collectedQuestionnaireAnswers,
        projectCategories: finalSelectedCategories,
      );

      if (mounted) {
        setState(() {
          _latestAIExpansionResult = analysisResult; // analysisResult is already ExpandedProjectIdea
        });

        final ExpandedProjectIdea structuredResult = analysisResult;
        StringBuffer dialogMessage = StringBuffer();
        dialogMessage.writeln("AI Analysis (Mock):");
        dialogMessage.writeln("===================");
        dialogMessage.writeln("Summary: ${structuredResult.summary}");
        dialogMessage.writeln("\nSuggested Features:");
        if (structuredResult.features.isEmpty) {
          dialogMessage.writeln("- None suggested at this time.");
        } else {
          for (var feature in structuredResult.features.take(3)) {
            dialogMessage.writeln("- ${feature.name}: ${feature.description}");
          }
          if (structuredResult.features.length > 3) {
            dialogMessage.writeln("- ...and more.");
          }
        }
        dialogMessage.writeln("\nPotential Risks:");
        if (structuredResult.risks.isEmpty) {
          dialogMessage.writeln("- None identified at this time.");
        } else {
          for (var risk in structuredResult.risks.take(2)) {
            dialogMessage.writeln("- ${risk.description} (Mitigation: ${risk.mitigation})");
          }
          if (structuredResult.risks.length > 2) {
            dialogMessage.writeln("- ...and more.");
          }
        }
        showMacosAlertDialog(
          context: context,
          builder: (_) => MacosAlertDialog(
            appIcon: const FlutterLogo(size: 56),
            title: Text('Project Expansion Analysis', style: MacosTheme.of(context).typography.headline),
            message: Text(dialogMessage.toString(), style: MacosTheme.of(context).typography.body),
            primaryButton: PushButton(
              buttonSize: ButtonSize.large,
              child: const Text('OK'),
              onPressed: () => Navigator.of(context).pop(),
            ),
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        showMacosAlertDialog(
          context: context,
          builder: (_) => MacosAlertDialog(
            appIcon: const MacosIcon(CupertinoIcons.exclamationmark_circle, color: MacosColors.systemRed, size: 56),
            title: Text('Error', style: MacosTheme.of(context).typography.headline),
            message: Text('An error occurred during AI analysis: ${e.toString()}', style: MacosTheme.of(context).typography.body),
            primaryButton: PushButton(
              buttonSize: ButtonSize.large,
              child: const Text('OK'),
              onPressed: () => Navigator.of(context).pop(),
            ),
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() {
          _isLoading = false;
        });
      }
    }
  }

  Future<void> _handleSaveProject() async {
    if (_projectConceptController.text.trim().isEmpty && _latestAIExpansionResult == null) {
      showMacosAlertDialog(
        context: context,
        builder: (_) => MacosAlertDialog(
          appIcon: const MacosIcon(CupertinoIcons.exclamationmark_triangle, size: 56),
          title: Text('Cannot Save Project', style: MacosTheme.of(context).typography.headline),
          message: Text('Please enter a project concept or analyze an idea first.', style: MacosTheme.of(context).typography.body),
          primaryButton: PushButton(
            buttonSize: ButtonSize.large,
            child: const Text('OK'),
            onPressed: () => Navigator.of(context).pop(),
          ),
        ),
      );
      return;
    }

    String? projectTitle = await _showProjectTitleDialog();
    if (projectTitle == null || projectTitle.trim().isEmpty) {
      if (mounted) {
        showMacosAlertDialog(
          context: context,
          builder: (_) => MacosAlertDialog(
            appIcon: const MacosIcon(CupertinoIcons.info_circle, size: 56),
            title: Text('Save Canceled', style: MacosTheme.of(context).typography.headline),
            message: Text('Project title is required to save.', style: MacosTheme.of(context).typography.body),
            primaryButton: PushButton(
              buttonSize: ButtonSize.large,
              child: const Text('OK'),
              onPressed: () => Navigator.of(context).pop(),
            ),
          ),
        );
      }
      return;
    }

    final concept = _projectConceptController.text.trim();
    final goals = _projectGoalsController.text.trim();
    final audience = _targetAudienceController.text.trim();

    Map<String, String> collectedQuestionnaireAnswers = {};
    if (_showGuidedQuestions) {
      _guidedQuestionControllers.forEach((id, controller) {
        if (controller.text.trim().isNotEmpty) {
          final question = _guidedQuestionList.firstWhere((q) => q.id == id);
          collectedQuestionnaireAnswers[question.text] = controller.text.trim();
        }
      });
    }

    Map<String, String> finalSelectedCategories = {};
    _selectedCategories.forEach((categoryName, selectedOption) {
      if (selectedOption != null && selectedOption.isNotEmpty) {
        finalSelectedCategories[categoryName] = selectedOption;
      }
    });

    final now = DateTime.now();
    // final String projectId = Uuid().v4(); // Old way
    final storageService = ref.read(storageServiceProvider); // Use provider
    final String projectId = await storageService.generateUniqueId(); // ID from service

    final projectData = ProjectData(
      id: projectId,
      title: projectTitle.trim(),
      projectConcept: concept,
      projectGoals: goals.isNotEmpty ? goals : null,
      targetAudience: audience.isNotEmpty ? audience : null,
      questionnaireAnswers: collectedQuestionnaireAnswers.isNotEmpty ? collectedQuestionnaireAnswers : null,
      projectCategories: finalSelectedCategories.isNotEmpty ? finalSelectedCategories : null,
      aiExpansionResults: _latestAIExpansionResult,
      createdAt: now,
      lastUpdatedAt: now,
    );

    try {
      await storageService.saveProject(projectData); // Actual save call

      if (mounted) {
        showMacosAlertDialog(
          context: context,
          builder: (_) => MacosAlertDialog(
            appIcon: const MacosIcon(CupertinoIcons.check_mark_circled, size: 56, color: MacosColors.systemGreen),
            title: Text('Project Saved', style: MacosTheme.of(context).typography.headline),
            message: Text('Project "$projectTitle" has been saved successfully.', style: MacosTheme.of(context).typography.body),
            primaryButton: PushButton(
              buttonSize: ButtonSize.large,
              child: const Text('OK'),
              onPressed: () => Navigator.of(context).pop(),
            ),
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        showMacosAlertDialog(
          context: context,
          builder: (_) => MacosAlertDialog(
            appIcon: const MacosIcon(CupertinoIcons.xmark_octagon, size: 56, color: MacosColors.systemRed),
            title: Text('Save Failed', style: MacosTheme.of(context).typography.headline),
            message: Text('Could not save the project: ${e.toString()}', style: MacosTheme.of(context).typography.body),
            primaryButton: PushButton(
              buttonSize: ButtonSize.large,
              child: const Text('OK'),
              onPressed: () => Navigator.of(context).pop(),
            ),
          ),
        );
      }
    }
  }

  Future<String?> _showProjectTitleDialog() async {
    final TextEditingController titleController = TextEditingController();
    return showMacosAlertDialog<String>(
      context: context,
      builder: (_) => MacosAlertDialog(
        appIcon: const MacosIcon(CupertinoIcons.pencil_outline, size: 56),
        title: Text('Enter Project Title', style: MacosTheme.of(context).typography.headline),
        message: MacosTextField(
          controller: titleController,
          placeholder: 'My Awesome Project',
          autofocus: true,
        ),
        primaryButton: PushButton(
          buttonSize: ButtonSize.large,
          child: const Text('Save'),
          onPressed: () {
            Navigator.of(context).pop(titleController.text);
          },
        ),
        secondaryButton: PushButton(
          buttonSize: ButtonSize.large,
          secondary: true,
          child: const Text('Cancel'),
          onPressed: () {
            Navigator.of(context).pop(null);
          },
        ),
      ),
    );
  }
}
